name: HPS STM32G0 tests
on:
  push:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: antmicro/renode-test-action@v2.0.0
        with:
            renode-version: 'latest'
            tests-to-run: 'hps.robot'

      - name: Archive tests results
        uses: actions/upload-artifact@v2
        with:
            name: test-results
            path: |
                report.html
                log.html
                robot_output.xml
